/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
//Obxetivo: Dar de alta novos usuario, Dar de baixa usuarios existentes e Editar información dos existentes
/*Por ahora: busca tus obras, inserta obras(realizar restauracion) si son antiguidades <-hacer que se seleccione,
        buscar todas obras y filtrar por nombre si quieres, lo dejé en finalizar restauracion que falla en algo
    Me hace falta obtener la fecha actual para completar e realizar y finalizar restaurador
 */
package gui;

import aplicacion.TipoEstado;
import aplicacion.Usuario;
import javax.swing.ComboBoxModel;
import aplicacion.TipoUsuario;

public class VRestaurador extends javax.swing.JDialog {
    /**
     * Creates new form VAviso
     */
    private aplicacion.FachadaAplicacion fa;
    private String IDRestaurador;

    public VRestaurador(aplicacion.FachadaAplicacion fa) {
        this.fa = fa;
        initComponents();
        this.setTitle("Menú de Restauracióon");
        //this.setVisible(false);
        //btnGuardar.setEnabled(false);
    }

    public VRestaurador(aplicacion.FachadaAplicacion fa, String Restaurador) {
        this.fa = fa;
        initComponents();
        this.setTitle("Menú de Restauración");
        this.IDRestaurador=Restaurador;
        System.out.println("Loggeado como:"+IDRestaurador);
        this.Usuario.setText(Restaurador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        btnCerrar = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnBuscarDemasObras = new javax.swing.JButton();
        campoNombre = new javax.swing.JTextField();
        campoEstado = new javax.swing.JTextField();
        campoObra = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        RelizarRest = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaDemasObras = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        campoCodigo = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        FinalizarObra = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTusObras = new javax.swing.JTable();
        campoTuCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TEstado = new javax.swing.JComboBox(TipoEstado.values());
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        campoTuObra = new javax.swing.JTextField();
        Usuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre");

        btnBuscarDemasObras.setText("Buscar");
        btnBuscarDemasObras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDemasObrasActionPerformed(evt);
            }
        });

        campoEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEstadoActionPerformed(evt);
            }
        });

        campoObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoObraActionPerformed(evt);
            }
        });

        jLabel5.setText("Obra:");

        jLabel6.setText("Estado:");

        RelizarRest.setText("Realizar Restauración");
        RelizarRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelizarRestActionPerformed(evt);
            }
        });

        TablaDemasObras.setModel(new ModeloTablaDemasObras());
        TablaDemasObras.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                TablaDemasObrasMouseWheelMoved(evt);
            }
        });
        TablaDemasObras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaDemasObrasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaDemasObras);

        jLabel7.setText("Código:");

        campoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCodigoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoObra, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(96, 96, 96)
                .addComponent(RelizarRest, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscarDemasObras)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 807, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarDemasObras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(RelizarRest, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(20, 20, 20))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(96, Short.MAX_VALUE)))
        );

        jTabbedPane2.addTab("Demás Obras", jPanel2);

        FinalizarObra.setText("Finalizar Restauración");
        FinalizarObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalizarObraActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tablaTusObras.setModel(new ModeloTablaTusObras());
        tablaTusObras.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                tablaTusObrasMouseWheelMoved(evt);
            }
        });
        tablaTusObras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaTusObrasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaTusObras);

        campoTuCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTuCodigoActionPerformed(evt);
            }
        });

        jLabel3.setText("Codigo:");

        jLabel8.setText("Nuevo Estado:");

        jLabel9.setText("Obra:");

        campoTuObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTuObraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoTuObra, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoTuCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addComponent(FinalizarObra)
                .addGap(100, 100, 100))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnBuscar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(FinalizarObra, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoTuObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoTuCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addGap(37, 37, 37))
        );

        jTabbedPane2.addTab("Tus Obras", jPanel1);

        Usuario.setText("Usuario");

        jLabel1.setText("Usuario:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrar))
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrar)
                    .addComponent(Usuario)
                    .addComponent(jLabel1)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void tablaTusObrasMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_tablaTusObrasMouseWheelMoved

    }//GEN-LAST:event_tablaTusObrasMouseWheelMoved

    private void campoEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEstadoActionPerformed
    }//GEN-LAST:event_campoEstadoActionPerformed

    private void campoObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoObraActionPerformed
    }//GEN-LAST:event_campoObraActionPerformed

    private void TablaDemasObrasMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_TablaDemasObrasMouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaDemasObrasMouseWheelMoved

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        ModeloTablaTusObras m;
        //Usuario primero;
        m = (ModeloTablaTusObras) tablaTusObras.getModel();
        m.setFilas(fa.obtenerObrasRestaurador(this.IDRestaurador));
        //fa.obtenerObras(this.IDRestaurador);
        //(buscaId.getText().isEmpty())?null:Integer.parseInt(buscaId.getText())
        if (m.getRowCount() > 0) {
            tablaTusObras.setRowSelectionInterval(0, 0);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnBuscarDemasObrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDemasObrasActionPerformed
        ModeloTablaDemasObras m;
        m=(ModeloTablaDemasObras) TablaDemasObras.getModel();
        //System.out.println("vrest");
        if(campoNombre.getText().isEmpty()) {
            m.setFilas(fa.obtenerTodasObras());
        } else {
            m.setFilas(fa.obtenerDemasObras(campoNombre.getText()));
        }

        //(buscaId.getText().isEmpty())?null:Integer.parseInt(buscaId.getText())
        if (m.getRowCount() > 0) {
            TablaDemasObras.setRowSelectionInterval(0, 0);
        }
    }//GEN-LAST:event_btnBuscarDemasObrasActionPerformed

    private void RelizarRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelizarRestActionPerformed
        //if(!campoNombre.getText().isEmpty()||!campoEstado.getText().isEmpty())
        //añadir esa obra o texto
        if(!campoCodigo.getText().isEmpty())
            fa.insertaRestauracion(Integer.valueOf(campoCodigo.getText()), this.IDRestaurador);
    }//GEN-LAST:event_RelizarRestActionPerformed

    private void campoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCodigoActionPerformed

    private void FinalizarObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalizarObraActionPerformed
        if(!campoTuCodigo.getText().isEmpty())
            fa.finalizaRestauracion(Integer.valueOf(campoTuCodigo.getText()), this.IDRestaurador, (TipoEstado) TEstado.getSelectedItem());
        else System.out.println("falta indicar la obra");
    }//GEN-LAST:event_FinalizarObraActionPerformed

    private void campoTuCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTuCodigoActionPerformed

    }//GEN-LAST:event_campoTuCodigoActionPerformed

    private void tablaTusObrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaTusObrasMouseClicked
        int row = tablaTusObras.rowAtPoint(evt.getPoint());
        
        System.out.println(tablaTusObras.getValueAt(row, 0));
        System.out.println(tablaTusObras.getValueAt(row, 1));
        System.out.println(tablaTusObras.getValueAt(row, 2));
        campoTuObra.setText(tablaTusObras.getValueAt(row, 0).toString());
        campoTuCodigo.setText(tablaTusObras.getValueAt(row, 4).toString());
    }//GEN-LAST:event_tablaTusObrasMouseClicked

    private void campoTuObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTuObraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTuObraActionPerformed

    private void TablaDemasObrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDemasObrasMouseClicked
        int row = TablaDemasObras.rowAtPoint(evt.getPoint());
        campoObra.setText(TablaDemasObras.getValueAt(row, 0).toString());
        campoEstado.setText(TablaDemasObras.getValueAt(row, 1).toString());
        campoCodigo.setText(TablaDemasObras.getValueAt(row, 2).toString());
    }//GEN-LAST:event_TablaDemasObrasMouseClicked

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FinalizarObra;
    private javax.swing.JButton RelizarRest;
    private javax.swing.JComboBox TEstado;
    private javax.swing.JTable TablaDemasObras;
    private javax.swing.JLabel Usuario;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarDemasObras;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JTextField campoCodigo;
    private javax.swing.JTextField campoEstado;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoObra;
    private javax.swing.JTextField campoTuCodigo;
    private javax.swing.JTextField campoTuObra;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable tablaTusObras;
    // End of variables declaration//GEN-END:variables

    public void buscarUsuarios() {
    }
}
