/*
Feito:Buscar usuario por id, gardar novos usuarios, Borrar Usuario, actualizar usuario existente,
Pendente: meter por defecto primeiro da lista nos JTextFields, Buscar por nombre tamen
Opcional: podese facer unha consulta máis complexa aqui
 */

package gui;
import aplicacion.Usuario;
import javax.swing.ComboBoxModel;
import aplicacion.TipoUsuario;
/**
 *
 * @author alumno
 */
public class VUsuario extends javax.swing.JDialog {

    /**
     * Creates new form VAviso
     */
    private aplicacion.FachadaAplicacion fa;
    private String IDUsuario;
    
    
    
    public VUsuario(aplicacion.FachadaAplicacion fa) {
        this.fa=fa;
        initComponents();
        this.setTitle("Gestión de Usuarios");
        this.setVisible(false);
       // btnGuardar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        btnCerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        insertaClave = new javax.swing.JPasswordField();
        insertaIDUsuario = new javax.swing.JTextField();
        insertaDireccion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        insertaTelefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        insertaNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TUsuario = new javax.swing.JComboBox(TipoUsuario.values());
        btnBorrar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        buscaNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        buscaID = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaUsers = new javax.swing.JTable();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        jLabel1.setText("ID:");

        jLabel2.setText("Clave:");

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        insertaClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertaClaveActionPerformed(evt);
            }
        });

        insertaIDUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertaIDUsuarioActionPerformed(evt);
            }
        });

        insertaDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertaDireccionActionPerformed(evt);
            }
        });

        jLabel3.setText("Dirección:");

        jLabel4.setText("Teléfono:");

        insertaTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertaTelefonoActionPerformed(evt);
            }
        });

        jLabel5.setText("Nombre:");

        insertaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertaNombreActionPerformed(evt);
            }
        });

        jLabel6.setText("E Administrador");

        TUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TUsuarioActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        buscaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaNombreActionPerformed(evt);
            }
        });

        jLabel7.setText("ID:");

        buscaID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaIDActionPerformed(evt);
            }
        });

        jLabel8.setText("Nombre:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        TablaUsers.setModel(new ModeloTablaUsuarios());
        TablaUsers.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                TablaUsersMouseWheelMoved(evt);
            }
        });
        jScrollPane1.setViewportView(TablaUsers);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(insertaIDUsuario))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(insertaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buscaID, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buscaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnBuscar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(6, 6, 6)
                                                .addComponent(insertaTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(51, 51, 51)
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(insertaDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(insertaClave, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNuevo)
                                .addGap(50, 50, 50)
                                .addComponent(btnGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBorrar)
                                .addGap(56, 56, 56)
                                .addComponent(btnCerrar)))
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(buscaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(buscaID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(insertaIDUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(insertaClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(TUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(insertaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(insertaTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(insertaDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrar)
                    .addComponent(btnNuevo)
                    .addComponent(btnBorrar)
                    .addComponent(btnGuardar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    
    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        insertaIDUsuario.setText(null);
        insertaClave.setText(null);
        insertaNombre.setText(null);
        insertaTelefono.setText(null);
        insertaDireccion.setText(null);
        btnGuardar.setEnabled(true);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void insertaIDUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertaIDUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertaIDUsuarioActionPerformed

    private void insertaClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertaClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertaClaveActionPerformed

    private void insertaDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertaDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertaDireccionActionPerformed

    private void insertaTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertaTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertaTelefonoActionPerformed

    private void insertaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertaNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insertaNombreActionPerformed

    private void TUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TUsuarioActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TUsuarioActionPerformed

    private void buscaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscaNombreActionPerformed

    private void buscaIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaIDActionPerformed
      
    }//GEN-LAST:event_buscaIDActionPerformed

    private void TablaUsersMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_TablaUsersMouseWheelMoved
       
    }//GEN-LAST:event_TablaUsersMouseWheelMoved

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarUsuarios();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if(insertaIDUsuario.getText().isEmpty() || insertaClave.getText().isEmpty() || insertaNombre.getText().isEmpty() || insertaTelefono.getText().isEmpty() || insertaDireccion.getText().isEmpty()){
            System.out.println("error: HAY ALGUN CAMPO DE USUARIO VACIO");
        }else{
        Usuario u;
        boolean admin;
        if(TUsuario.getSelectedItem()==TipoUsuario.Administrador) admin=true;
        else admin=false;
        //(String idUsuario, String clave, String nombre, String direccion, String telefono, boolean esAdmin)
        //u=new Usuario(insertaIDUsuario.getText(),insertaClave.getText(),insertaNombre.getText(),insertaDireccion.getText(),insertaTelefono.getText(),(boolean) TUsuario.getSelectedItem());
        u=new Usuario(insertaIDUsuario.getText(),insertaClave.getText(),insertaNombre.getText(),insertaDireccion.getText(),insertaTelefono.getText(), admin);
         fa.insertarUsuario(u);
         btnGuardar.setEnabled(false);
        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        String idUsuario = insertaIDUsuario.getText();
        fa.borrarUsuario(idUsuario);
    }//GEN-LAST:event_btnBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox TUsuario;
    private javax.swing.JTable TablaUsers;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JTextField buscaID;
    private javax.swing.JTextField buscaNombre;
    private javax.swing.JPasswordField insertaClave;
    private javax.swing.JTextField insertaDireccion;
    private javax.swing.JTextField insertaIDUsuario;
    private javax.swing.JTextField insertaNombre;
    private javax.swing.JTextField insertaTelefono;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables


    
    public void buscarUsuarios(){
        ModeloTablaUsuarios m;
        //Usuario primero;
        m=(ModeloTablaUsuarios) TablaUsers.getModel();
        m.setFilas(fa.obtenerUsuarios(buscaID.getText(), buscaNombre.getText().isEmpty()?null:buscaNombre.getText()));
        //(buscaId.getText().isEmpty())?null:Integer.parseInt(buscaId.getText())
        if (m.getRowCount() > 0) {
            TablaUsers.setRowSelectionInterval(0, 0);

//            primero=fa.damePrimero(buscaID.getText(), buscaNombre.getText().isEmpty()?null:buscaNombre.getText());
//            insertaIDUsuario.setText(primero.getIdUsuario());
//            insertaNUsuario.setText(primero.getNombre());
//            insertaClave.setText(primero.getClave());
//            TUsuario.setSelectedItem(primero.getTipoUsuario());
//            insertaMail.setText(primero.getEmail());
//            insertaDireccion.setText(primero.getDireccion());
            //System.out.println(primero.getClave()+" "+primero.getNombre());
            //buscaID.setText(m.getValueAt(0, 0).toString());
            
        }  
    }


    
    public void insertarUsuario(Usuario u){
     
    }
}
